//
// Created by pcx on 8/13/2022.
//

#ifndef STUDENTS_MANAGEMENT_SOFTWARE_U_FILEMANIPULATEMODULE_H
#define STUDENTS_MANAGEMENT_SOFTWARE_U_FILEMANIPULATEMODULE_H
#include<stdio.h>
#include "studentsManagementSoftware/u_dataStruct.h"






#endif //STUDENTS_MANAGEMENT_SOFTWARE_U_FILEMANIPULATEMODULE_H
